[package]
name = "counter_cli"
version = "0.1.0"
edition.workspace = true

[dependencies]
serde_json = { workspace = true }
elmio-core = { workspace = true }
url = { workspace = true }
counter_core = { path = "../counter_core" }
